---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: zhanggongsw/bosh
inputs:
  - name: bosh-cpi-release
  - name: bosh-cpi-final-release
outputs:
  - name: promote
run:
  path: bosh-cpi-release/ci/tasks/build-patch.sh
