---
platform: linux
image: docker:///cloudfoundry/bosh-lite-ci

inputs:
  - name: bosh-softlayer-cpi
    path: gopath/src/github.com/maximilien/bosh-softlayer-cpi

run:
  path: gopath/src/github.com/maximilien/bosh-softlayer-cpi/bin/build